name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        example: [examples/FirmwareVersion/FirmwareVersion.ino]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Download external library
        run: |
          wget https://github.com/zanac73/FirmwareVersion/archive/master.zip -O /tmp/FirmwareVersion.zip
          unzip /tmp/FirmwareVersion.zip -d /tmp        
      - name: Run PlatformIO
        run: pio ci --lib="." --lib="/tmp/FirmwareVersion-master" --board=uno --board=teensy31 --board=due
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}